---
- hosts: backend
  become: yes
  tasks:
    - name: Install Netdata
      apt:
        deb: https://packagecloud.io/netdata/netdata/packages/ubuntu/focal/netdata_1.36.1_amd64.deb
        state: present
      when: ansible_os_family == "Debian"

    - name: Ensure Netdata is running
      service:
        name: netdata
        state: started
