---
- hosts: c8.local
  become: yes
  tasks:
    - name: Disable SELinux
      command: setenforce 0
      ignore_errors: yes

    - name: Disable firewalld
      service:
        name: firewalld
        state: stopped
        enabled: no
